### ISSUE TITLE
Update to JupyterLab 4

### ISSUE THREAD

**Issue by thewtex** [imjoy-team/imjoy-jupyterlab-extension#2]
JupyterLab 4 has been released as stable and the package pin to version 3 seem to results in downgrades of jupyter packages and kernel crashes.

@oeway

**Comment by thewtex** [comment]
3.X to 4.X extension migration guide: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

**Comment by oeway** [comment]
Thank you for the heads up! Will look into this!

**Comment by thewtex** [comment]
@oeway thank you!!
