### ISSUE TITLE
No joy yet with version 0.1.20

### ISSUE THREAD

**Issue by thewtex** [imjoy-team/imjoy-jupyterlab-extension#4]
@oeway thanks for the recent bump for Jupyter 4!

Installation succeeds, and I do see:

```
fd:1 JupyterLab extension imjoy-jupyterlab-extension is activated!
```

in the browser console. However, there is no ImJoy icon in the notebook bar or cell output either with the test at the bottom of the project README or with itkwidgets.

![image](https://github.com/imjoy-team/imjoy-jupyterlab-extension/assets/25432/a7b72f79-b178-4cc4-b054-a54a7389134f)

**Comment by oeway** [comment]
That's wired, I tested it with the latest Jupyter lab and it seems to be working. Will check when I have a slot.

**Comment by oeway** [comment]
@thewtex Thanks, I have just fixed it, please try it with `imjoy-jupyterlab-extension==0.1.21`. The previous version miss several files (removed by the upgrades scripts) and somehow my test notebook used the old version.

~~Anyway, it suppose to work now, if not please reopen the issue!~~
Edit: oops, it seems the new extension is not loading, I will see how I can fix it and get back to you.

**Comment by thewtex** [comment]
@oeway thanks for your attention to this!

**Comment by oeway** [comment]
Hi @thewtex Finally, sorry for the delay! The new jupyterlab should be supported now. 
https://pypi.org/project/imjoy-jupyterlab-extension/

P.S. It was not easy to get it work, the whole jupyter extension system is so fragile and I couldn't easily get things work together.

**Comment by thewtex** [comment]
@oeway thank you so much for the effort and attention to this! Awesome to have it updated!

> P.S. It was not easy to get it work, the whole jupyter extension system is so fragile and I couldn't easily get things work together.

Yes, I have also experienced this :-)
